export const MATCH_STATUS = {
    PREGAME                               : 0,
    INPROGRESS                            : 1,
    FINAL                                 : 2,
    POSTPONED                             : 3,
    SUSPENDED                             : 4,
    FORFEIT_BY_AWAY                       : 5,
    FORFEIT_BY_HOME                       : 6,
    CANCELLED                             : 7,
    FORFEIT_BY_BOTH_TEAMS                 : 8,
    FORFEIT_BY_AWAY_TEAMCONFERENCE_ONLY   : 9,
    FORFEIT_BY_HOME_TEAMCONFERENCE_ONLY   : 10,
    VACATED_BY_BOTH_TEAMS                 : 11,
    VACATED_BY_AWAY_TEAM                  : 12,
    VACATED_BY_HOME_TEAM                  : 13,
    FORFEIT_AWAY_VACATED_HOME             : 14,
    FORFEIT_HOME_VACATED_AWAY             : 15,
    DELAYED                               : 16,
    HALF_TIME                             : 17,
}